service: EmployeeListApi
  
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  
provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions:
  createEmployee:
    handler: src/modules/employees/useCases/createEmployeeProfile/createEmployeeController.handle
    events:
      - http:
          path: /createEmployee
          method: POST
          cors: true
  listEmployees:
    handler: src/modules/employees/useCases/listEmployees/listEmployeesController.handle
    events:
      - http:
          path: /listEmployees
          method: GET
          cors: 
  deleteEmployee:
    handler: src/modules/employees/useCases/deleteEmployeeProfile/deleteEmployeeController.handle
    events:
      - http:
          path: /deleteEmployee/{id}
          method: DELETE
          cors: true
  viewEmployee:
    handler: src/modules/employees/useCases/viewEmployeeProfile/viewEmployeeController.handle
    events:
      - http:
          path: /viewEmployee/{id}
          method: GET
          cors: true
  updateEmployee:
    handler: src/modules/employees/useCases/updateEmployeeProfile/updateEmployeeController.handle
    events:
      - http:
          path: /updateEmployee/{id}
          method: PATCH
          cors: true

resources:
  Resources:
    dbEmployees:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: employees
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions: 
            - AttributeName: id
              AttributeType: S
        KeySchema:
            - AttributeName: id
              KeyType: HASH
            